version: '3.8'

services:
  phpserver:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: phpserver
    ports:
      - "8070:80"                       # Acesso externo via navegador
    volumes:
      - ./vt_dash:/var/www/html        # Código-fonte da aplicação PHP
    working_dir: /var/www/html
    restart: always
    depends_on:
      - db                             # Aguarda o container do banco iniciar
    environment:
      DB_HOST: db                      # Nome do container do banco de dados
      DB_PORT: 3306                    # Porta interna do MySQL
      DB_NAME: dashboard
      DB_USER: root
      DB_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Para chamadas localhost externas

  db:
    image: mysql:8.0
    container_name: mysql_vtdash
    restart: always
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3317:3306"                    # Acesso externo ao MySQL (ex: localhost:3317)
    volumes:
      - mysql_data:/var/lib/mysql     # Persistência dos dados
      - ./vt_dash/dashboard.sql:/docker-entrypoint-initdb.d/dashboard.sql:ro  # Carga inicial do banco

volumes:
  mysql_data:
