version: '3.8'

services:
  phpserver:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: phpserver
    ports:
      - "8070:80"
    volumes:
      - ./vt_dash:/var/www/html
    working_dir: /var/www/html
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db            
      DB_PORT: 3306       
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    container_name: mysql_vtdash
    restart: always
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3317:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./vt_dash/dashboard.sql:/docker-entrypoint-initdb.d/dashboard.sql:ro

volumes:
  mysql_data:
